// Image collections
export const imgCollections = [
    {name: 'NatureImage1', category: 'nature', url: './Images/nature/img1.jpeg'},
    {name: 'NatureImage2', category: 'nature', url: './Images/nature/img2.jpeg'},
    {name: 'NatureImage3', category: 'nature', url: './Images/nature/img3.jpeg'},
    {name: 'NatureImage4', category: 'nature', url: './Images/nature/img4.jpeg'},
    {name: 'NatureImage5', category: 'nature', url: './Images/nature/img5.jpeg'},
    {name: 'NatureImage6', category: 'nature', url: './Images/nature/img6.jpeg'},
    {name: 'NatureImage7', category: 'nature', url: './Images/nature/img7.jpeg'},
    {name: 'NatureImage8', category: 'nature', url: './Images/nature/img8.jpeg'},
    {name: 'NatureImage9', category: 'nature', url: './Images/nature/img9.jpeg'},
    {name: 'NatureImage10', category: 'nature', url: './Images/nature/img10.jpeg'},

    {name: 'CityImage1', category: 'city', url: './Images/city/img1.jpeg'},
    {name: 'CityImage2', category: 'city', url: './Images/city/img2.jpeg'},
    {name: 'CityImage3', category: 'city', url: './Images/city/img3.jpeg'},
    {name: 'CityImage4', category: 'city', url: './Images/city/img4.jpeg'},
    {name: 'CityImage5', category: 'city', url: './Images/city/img5.jpeg'},
    {name: 'CityImage6', category: 'city', url: './Images/city/img6.jpeg'},
    {name: 'CityImage7', category: 'city', url: './Images/city/img7.jpeg'},
    {name: 'CityImage8', category: 'city', url: './Images/city/img8.jpeg'},
    {name: 'CityImage9', category: 'city', url: './Images/city/img9.jpeg'},
    {name: 'CityImage10', category: 'city', url: './Images/city/img10.jpeg'},

    {name: 'AnimalImage1', category: 'animal', url: './Images/animal/img1.jpeg'},
    {name: 'AnimalImage2', category: 'animal', url: './Images/animal/img2.jpeg'},
    {name: 'AnimalImage3', category: 'animal', url: './Images/animal/img3.jpeg'},
    {name: 'AnimalImage4', category: 'animal', url: './Images/animal/img4.jpeg'},
    {name: 'AnimalImage5', category: 'animal', url: './Images/animal/img5.jpeg'},
    {name: 'Animalmage6', category: 'animal', url: './Images/animal/img6.jpeg'},
    {name: 'AnimalImage7', category: 'animal', url: './Images/animal/img7.jpeg'},
    {name: 'AnimalImage8', category: 'animal', url: './Images/animal/img8.jpeg'},
    {name: 'AnimalImage9', category: 'animal', url: './Images/animal/img9.jpg'},
    {name: 'AnimalImage10', category: 'animal', url: './Images/animal/img10.jpeg'},

    {name: 'CarImage1', category: 'car', url: './Images/car/img1.jpeg'},
    {name: 'CarImage2', category: 'car', url: './Images/car/img2.jpeg'},
    {name: 'CarImage3', category: 'car', url: './Images/car/img3.jpeg'},
    {name: 'CarImage4', category: 'car', url: './Images/car/img4.jpeg'},
    {name: 'CarImage5', category: 'car', url: './Images/car/img5.jpeg'},
    {name: 'CarImage6', category: 'car', url: './Images/car/img6.jpeg'},
    {name: 'CarImage7', category: 'car', url: './Images/car/img7.jpeg'},
    {name: 'CarImage8', category: 'car', url: './Images/car/img8.jpeg'},
    {name: 'CarImage9', category: 'car', url: './Images/car/img9.jpeg'},
    {name: 'CarImage10', category: 'car', url: './Images/car/img10.jpeg'},

]